use_frameworks!

platform :ios, '10.0'

target 'TestFly_Example' do
  
  pod 'libPhoneNumber-iOS', '~> 0.8'
  pod 'TestFly', :path => '../'

  target 'TestFly_Tests' do
    inherit! :search_paths

    
  end
end
